/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "concserver.h"

int *
ginomeno_dianismaton_1_svc(Dianismata *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 0;
	int n = argp->X.X_len;
	for (int i=0; i<n; i++){
		result += argp->X.X_val[i] * argp->Y.Y_val[i];
	}

	return &result;
}

MesesTimes *
mesitimi_1_svc(Dianismata *argp, struct svc_req *rqstp)
{
	static MesesTimes  result;

	int n = argp->X.X_len;
	double sumX = 0, sumY = 0;
	for (int i=0; i<n; i++){
		sumX += argp->X.X_val[i];
		sumY += argp->Y.Y_val[i];
	}
	result.Ex = sumX/n;
	result.Ey = sumY/n;

	return &result;
}

GinomenoEpistrofi *
ginomeno_1_svc(GinomenoEisodos *argp, struct svc_req *rqstp)
{
	static GinomenoEpistrofi  result;
	int n = argp->X.X_len;

       if (result.result.result_val != NULL) {
        free(result.result.result_val);
        result.result.result_val = NULL;
    }

        result.result.result_val = malloc(n * sizeof(double));
    result.result.result_len = n;

    for (int i = 0; i < n; i++)
        result.result.result_val[i] = argp->r * argp->X.X_val[i];


	return &result;
}
