/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "concserver.h"

bool_t
xdr_Dianismata (XDR *xdrs, Dianismata *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MesesTimes (XDR *xdrs, MesesTimes *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->Ex))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->Ey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GinomenoEisodos (XDR *xdrs, GinomenoEisodos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GinomenoEpistrofi (XDR *xdrs, GinomenoEpistrofi *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->result.result_val, (u_int *) &objp->result.result_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
