/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "concserver.h"


void
vectorops_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	Dianismata  ginomeno_dianismaton_1_arg;
	MesesTimes  *result_2;
	Dianismata  mesitimi_1_arg;
	GinomenoEpistrofi  *result_3;
	ScaleInput  ginomeno_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, VECTOROPS_PROG, VECTOROPS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ginomeno_dianismaton_1(&ginomeno_dianismaton_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = mesitimi_1(&mesitimi_1_arg, clnt);
	if (result_2 == (MesesTimes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = ginomeno_1(&ginomeno_1_arg, clnt);
	if (result_3 == (GinomenoEpistrofi *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	vectorops_prog_1 (host);
exit (0);
}
