/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONCSERVER_H_RPCGEN
#define _CONCSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Dianismata {
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct Dianismata Dianismata;

struct MesesTimes {
	double Ex;
	double Ey;
};
typedef struct MesesTimes MesesTimes;

struct GinomenoEisodos {
	double r;
	struct {
		u_int X_len;
		int *X_val;
	} X;
};
typedef struct GinomenoEisodos GinomenoEisodos;

struct GinomenoEpistrofi {
	struct {
		u_int result_len;
		double *result_val;
	} result;
};
typedef struct GinomenoEpistrofi GinomenoEpistrofi;

#define CONCSERVER_PROG 0x23451111
#define CONCSERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GINOMENO_DIANISMATON 1
extern  int * ginomeno_dianismaton_1(Dianismata *, CLIENT *);
extern  int * ginomeno_dianismaton_1_svc(Dianismata *, struct svc_req *);
#define MESITIMI 2
extern  MesesTimes * mesitimi_1(Dianismata *, CLIENT *);
extern  MesesTimes * mesitimi_1_svc(Dianismata *, struct svc_req *);
#define GINOMENO 3
extern  GinomenoEpistrofi * ginomeno_1(GinomenoEisodos *, CLIENT *);
extern  GinomenoEpistrofi * ginomeno_1_svc(GinomenoEisodos *, struct svc_req *);
extern int concserver_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GINOMENO_DIANISMATON 1
extern  int * ginomeno_dianismaton_1();
extern  int * ginomeno_dianismaton_1_svc();
#define MESITIMI 2
extern  MesesTimes * mesitimi_1();
extern  MesesTimes * mesitimi_1_svc();
#define GINOMENO 3
extern  GinomenoEpistrofi * ginomeno_1();
extern  GinomenoEpistrofi * ginomeno_1_svc();
extern int concserver_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Dianismata (XDR *, Dianismata*);
extern  bool_t xdr_MesesTimes (XDR *, MesesTimes*);
extern  bool_t xdr_GinomenoEisodos (XDR *, GinomenoEisodos*);
extern  bool_t xdr_GinomenoEpistrofi (XDR *, GinomenoEpistrofi*);

#else /* K&R C */
extern bool_t xdr_Dianismata ();
extern bool_t xdr_MesesTimes ();
extern bool_t xdr_GinomenoEisodos ();
extern bool_t xdr_GinomenoEpistrofi ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONCSERVER_H_RPCGEN */
